apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs.geolonia.com
  title: docs.geolonia.com
  annotations:
    github.com/project-slug: geolonia/docs.geolonia.com


spec:
  type: website
  owner: group:geolonia/maps-team
  lifecycle: production
  accessGrants:
    - team: group:geolonia/designers
      permission: maintain
  # accessGrants:
  #   - team: group:geolonia/team-name
  #     permission: write  # read | triage | write | maintain | admin
